version: '3.4'

services:
  schoollibraryapi:
    image: ${DOCKER_REGISTRY-}schoollibraryapi
    build:
      context: .
      dockerfile: SchoolLibraryAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4200:80"  